eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: spc-shopp-zuul
zuul:
  routes:
    api-a:
      path: /order/**
      service-id: spc-shopp-member
  host:
        connect-timeout-millis: 3000
        socket-timeout-millis: 3000    
ribbon:  
  ReadTimeout: 3000
  ConnectTimeout: 3000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000        