server:
  port: 8763
  context-path: /meessage
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: spc-shopp-message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: 15284307857@163.com
    password: a123456
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
########################################

msg: 
  subject: 小代,提示您会员注册成功邮件。
  text:  恭喜您的账户{},注册成功